[default.extend-words]


[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    ".gitignore",
    ".pre-commit-config.yaml",
    "Cargo.*",
    "readme.md",
    "deny.toml",
    "cargo-generate.toml",
    "target/*",
    "_typos.toml",
    "Cargo.lock",
    "Dockerfile",
    "docker-compose.yml",
    "migration/target/*",
    "tests/*",
]
